spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: ${GOOGLE_CLIENT_ID}
#            clientSecret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - email

redash:
  basic-auth-token: ${REDASH_BASIC_AUTH_TOKEN}