name: Backend testing

on:
  push:
    branches: [ $default-branch ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ $default-branch ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run tests
        working-directory: ./backend
        run: ./gradlew clean test

